[package]
name = "fibo"
version = "0.1.0"
authors = ["Vis Virial <visvirial@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-bigint = "0.4"

